[workspace]
members = ["tuts/", "tuts/topics/async/*",
"libs/axum-playground"  
# "libs/chatgpt_demo"
, "pro/rust-api-heroku", "libs/databases/redis/demo", "pro/basic-router", "libs/smol-demo"]
resolver = "2"
